version: "3.9"
services:
  web:
    build: ./docker/web
    container_name: sched_web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    environment:
      TZ: Asia/Tokyo
      DB_HOST: db
      DB_NAME: schedule_app
      DB_USER: app
      DB_PASS: apppass
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sched_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedule_app
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
      TZ: Asia/Tokyo
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sched_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata:
